# Generated by Django 4.1.3 on 2023-06-28 03:35

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionSaveList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='カテゴリー')),
                ('clothing', models.CharField(default='nothing', max_length=100, verbose_name='ジャンル')),
                ('season', models.CharField(default='オールシーズン', max_length=100, verbose_name='季節')),
                ('color', models.CharField(default='', max_length=10, verbose_name='ベースカラー')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='ブランド')),
                ('slug', models.IntegerField(verbose_name='固有ID')),
                ('description', models.TextField(verbose_name='説明')),
                ('author', models.IntegerField(verbose_name='作者アカウントID')),
                ('sex', models.CharField(default='自由', max_length=2, verbose_name='性別')),
                ('publish', models.BooleanField(default=False, verbose_name='公開')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ファッション一覧',
                'verbose_name_plural': 'ファッション一覧',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('price', models.IntegerField(verbose_name='値段')),
                ('category', models.CharField(max_length=100, verbose_name='カテゴリー')),
                ('brand', models.CharField(max_length=100, verbose_name='ブランド')),
                ('slug', models.SlugField(verbose_name='固有ID')),
                ('description', models.TextField(verbose_name='商品説明')),
                ('sex', models.CharField(choices=[('自由', '自由'), ('男性', '男性'), ('女性', '女性')], default='自由', max_length=5, verbose_name='性別')),
                ('color', models.CharField(choices=[('白', '白'), ('グレー', 'グレー'), ('黒', '黒'), ('ピンク', 'ピンク'), ('赤', '赤'), ('オレンジ', 'オレンジ'), ('ベージュ', 'ベージュ'), ('茶', '茶'), ('黄', '黄'), ('緑', '緑'), ('青', '青'), ('紫', '紫'), ('ネイビー', 'ネイビー'), ('カーキ', 'カーキ'), ('ゴールド', 'ゴールド'), ('アザー', 'アザー'), ('アイボリー', 'アイボリー'), ('オリーブ', 'オリーブ')], default='None', max_length=10, verbose_name='色')),
                ('image', models.ImageField(upload_to='products_images', verbose_name='イメージ画像')),
                ('upload_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'verbose_name': '商品一覧',
                'verbose_name_plural': '商品一覧',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('content', models.TextField(verbose_name='本文')),
            ],
            options={
                'verbose_name': 'ニュース一覧',
                'verbose_name_plural': 'ニュース一覧',
            },
        ),
        migrations.CreateModel(
            name='WebCam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='webcam', verbose_name='イメージ画像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.SlugField(verbose_name='アイテムID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('like', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評価')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('bought', models.BooleanField(default=False, verbose_name='購入者')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '商品レビュー一覧',
                'verbose_name_plural': '商品レビュー一覧',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '投稿一覧',
                'verbose_name_plural': '投稿一覧',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_change_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '支払一覧',
                'verbose_name_plural': '支払一覧',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '注文一覧',
                'verbose_name_plural': '注文一覧',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='app.orderitem')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '注文履歴',
                'verbose_name_plural': '注文履歴',
            },
        ),
        migrations.CreateModel(
            name='LikeForPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fashionsavelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_item', models.CharField(max_length=200, verbose_name='お気に入りアイテム')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'お気に入りアイテム一覧',
                'verbose_name_plural': 'お気に入りアイテム一覧',
            },
        ),
        migrations.CreateModel(
            name='FavoriteFashionListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_item', models.IntegerField(verbose_name='お気に入りファッションコーデ')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'お気に入りファッションコーデ一覧',
                'verbose_name_plural': 'お気に入りファッションコーデ一覧',
            },
        ),
        migrations.CreateModel(
            name='FashionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.SlugField(verbose_name='アイテムID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('like', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評価')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'カスタマイズコーデレビュー一覧',
                'verbose_name_plural': 'カスタマイズコーデレビュー一覧',
            },
        ),
        migrations.CreateModel(
            name='FashionItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('using_item', models.CharField(max_length=20, verbose_name='使用アイテム')),
                ('FSL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fashionsavelist')),
            ],
            options={
                'verbose_name': 'ファッション使用アイテム一覧',
                'verbose_name_plural': 'ファッション使用アイテム一覧',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, verbose_name='クーポンコード')),
                ('discount', models.IntegerField(default=0, verbose_name='割引')),
                ('end_date', models.DateTimeField(default=app.models.CouponWeek)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
