# Generated by Django 4.1.3 on 2023-08-08 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_editor_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='animations',
            field=models.IntegerField(default=-1, verbose_name='アニメーション'),
        ),
        migrations.AddField(
            model_name='editor',
            name='bgm',
            field=models.IntegerField(default=-1, verbose_name='BGM'),
        ),
        migrations.AddField(
            model_name='editor',
            name='cut',
            field=models.IntegerField(default=-1, verbose_name='カット'),
        ),
        migrations.AddField(
            model_name='editor',
            name='filter_effect',
            field=models.IntegerField(default=-1, verbose_name='フィルター'),
        ),
        migrations.AddField(
            model_name='editor',
            name='movie_format',
            field=models.IntegerField(default=-1, verbose_name='フォーマット'),
        ),
        migrations.AddField(
            model_name='editor',
            name='title',
            field=models.CharField(default='無題のタイトル', max_length=200, verbose_name='動画のタイトル'),
        ),
        migrations.AddField(
            model_name='editor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editor',
            name='voice',
            field=models.IntegerField(default=-1, verbose_name='音声'),
        ),
        migrations.AddField(
            model_name='editor',
            name='volume',
            field=models.IntegerField(default=-1, verbose_name='音声調整'),
        ),
    ]
