# Generated by Django 4.1.3 on 2023-08-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_editor_animations_remove_editor_bgm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'テンプレート', 'verbose_name_plural': 'テンプレート'},
        ),
    ]
