# Generated by Django 4.1.3 on 2023-08-08 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_template_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='メイン紹介文')),
                ('content_sub', models.TextField(verbose_name='サブ紹介文')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'verbose_name': 'メインページ紹介文',
                'verbose_name_plural': 'メインページ紹介文',
            },
        ),
    ]
