# Generated by Django 4.1.3 on 2023-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='banner',
            field=models.ImageField(default='a', upload_to='', verbose_name='バナー画像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='product',
            field=models.TextField(default='a', verbose_name='商品紹介文'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='product_image',
            field=models.ImageField(default='a', upload_to='', verbose_name='商品画像'),
            preserve_default=False,
        ),
    ]
