# Generated by Django 4.2.1 on 2023-08-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_editor_status_alter_editor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="editor",
            name="status",
            field=models.CharField(
                choices=[("1", "未着手"), ("2", "作成中"), ("3", "完了")],
                default="1",
                max_length=20,
            ),
        ),
    ]
