# Generated by Django 4.2.1 on 2023-08-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_editor_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="language",
            field=models.CharField(
                choices=[("ja", "日本語"), ("en", "英語"), ("ko", "韓国"), ("zh", "中国語")],
                default="ja",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="telopPos",
            field=models.CharField(
                choices=[("top", "上"), ("center", "真ん中"), ("bottom", "下")],
                default="top",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="voice",
            field=models.CharField(
                choices=[
                    ("0", "四国めたん あまあま"),
                    ("1", "ずんだもん あまあま"),
                    ("2", "四国めたん ノーマル"),
                    ("3", "ずんだもん ノーマル"),
                ],
                default="0",
                max_length=20,
            ),
        ),
    ]
