# Generated by Django 4.2.1 on 2023-08-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_template_language_template_teloppos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="model",
            field=models.CharField(
                choices=[
                    ("tiny", "ライト版"),
                    ("base", "お手軽版"),
                    ("small", "小性能"),
                    ("medium", "中性能"),
                    ("large", "高性能"),
                ],
                default="tiny",
                max_length=20,
            ),
        ),
    ]
