# Generated by Django 4.2.1 on 2023-08-27 04:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_template_translate_alter_template_voice"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="publish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="template",
            name="templateId",
            field=models.SlugField(
                default=app.models.create_id,
                max_length=30,
                unique=True,
                verbose_name="テンプレートID",
            ),
        ),
    ]
