# Generated by Django 4.2.1 on 2023-08-27 12:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_editor_editorid_editor_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="bgm",
            name="upload",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app.models.uploadFile,
                verbose_name="BGMファイル",
            ),
        ),
    ]
