# Generated by Django 4.2.1 on 2023-08-30 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_template_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="animations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.animations",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="bgm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.bgm",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="filter_effect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.filters",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="movie_format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.format",
            ),
        ),
    ]
