# Generated by Django 4.2.1 on 2023-08-30 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_model_publish_telop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publish",
            name="publishName",
            field=models.CharField(max_length=10, verbose_name="公開範囲"),
        ),
        migrations.AlterField(
            model_name="template",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.model",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="publish",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.publish",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="telopPos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.telop",
            ),
        ),
    ]
