# Generated by Django 4.1.3 on 2023-08-07 04:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to=app.models.uploadFile, verbose_name='動画ファイル')),
            ],
            options={
                'verbose_name': '動画編集',
                'verbose_name_plural': '動画編集',
            },
        ),
    ]
