# Generated by Django 4.1.3 on 2023-08-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_section_banner_section_product_section_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='banner',
            field=models.ImageField(default='Users/site/test.jpg', upload_to='', verbose_name='バナー画像'),
        ),
        migrations.AlterField(
            model_name='section',
            name='product_image',
            field=models.ImageField(default='Users/site/test.jpg', upload_to='', verbose_name='商品画像'),
        ),
    ]
