# Generated by Django 4.2.1 on 2023-08-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_editor_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="editor",
            name="edited",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="編集済みファイル"
            ),
        ),
    ]
