# Generated by Django 4.2.1 on 2023-08-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_editor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editor",
            name="edited",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="編集済みファイル"
            ),
        ),
    ]
