# Generated by Django 4.2.1 on 2023-08-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_template_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="translate",
            field=models.CharField(
                choices=[("", "翻訳なし"), ("translate", "英語へ翻訳する")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="voice",
            field=models.CharField(
                choices=[
                    ("-1", "ボイス無し"),
                    ("0", "四国めたん あまあま"),
                    ("1", "ずんだもん あまあま"),
                    ("2", "四国めたん ノーマル"),
                    ("3", "ずんだもん ノーマル"),
                ],
                default="-1",
                max_length=20,
            ),
        ),
    ]
