# Generated by Django 4.2.1 on 2023-08-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_language_alter_model_options_alter_template_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("VoiceId", models.CharField(max_length=10, verbose_name="モデル")),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
            ],
            options={
                "verbose_name": "読み上げ音声モデル一覧",
                "verbose_name_plural": "読み上げ音声モデル一覧",
            },
        ),
        migrations.AlterField(
            model_name="template",
            name="translate",
            field=models.CharField(
                blank=True,
                choices=[("None", "翻訳なし"), ("translate", "英語へ翻訳する")],
                default="None",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="voice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.voice",
            ),
        ),
    ]
