# Generated by Django 4.2.1 on 2023-08-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_alter_editor_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editor",
            name="publish",
            field=models.BooleanField(default=False),
        ),
    ]
